language: node_js
node_js:
    - 11
    - 10
    - 8

before_install:
    - npm i redrun -g
    - npm i eslint -g
    - npm i nyc -g
    - npm i coveralls -g

script:
  - npm run lint
  - npm run coverage && npm run report

notifications:
    email:
        on_success: never
        on_failure: change

sudo: false

