language: node_js
node_js:
    - 12
    - 10
    - 8

os:
    - linux

script:
  - npm run bootstrap
  - npm run lint
  - npm run coverage
  - cd packages/putout && npm run report

notifications:
    email:
        on_success: never
        on_failure: change

sudo: false
cache: false

