language: node_js
node_js:
    - 14
    - 12
    - 10

os:
    - linux
    - osx
    - windows

matrix:
    allow_failures:
        - os: windows
        - os: osx

script:
  - npm run bootstrap
  - npm run lint:ci
  - npm run coverage:long
  - npm run report

notifications:
    email:
        on_success: never
        on_failure: change

sudo: false
cache: false

