language: node_js
node_js:
  - 15
  - 14
script:
  - npm run bootstrap
  - npm run lint
  - npm run coverage:ci
  - npm run report
notifications:
  email:
    on_success: never
    on_failure: change
sudo: false
cache: false
