language: node_js
node_js:
    - 11

install: travis_retry npm i && lerna bootstrap

script:
  - npm run bootstrap
  - npm run lint
  - npm run coverage && npm run report

notifications:
    email:
        on_success: never
        on_failure: change

sudo: false

