language: node_js
node_js:
    - 13
    - 12
    - 10
    - 8

os:
    - linux
    - osx
    - windows

matrix:
    allow_failures:
        - os: windows

script:
  - npm run bootstrap
  - npm run lint
  - npm run coverage
  - npm run report

notifications:
    email:
        on_success: never
        on_failure: change

sudo: false
cache: false

