language: node_js
node_js:
    - 11

script:
  - npm run bootstrap --hoist
  - npm run lint
  - npm run coverage && npm run report

notifications:
    email:
        on_success: never
        on_failure: change

sudo: false

