name: Node CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      NAME: putout

    strategy:
      matrix:
        node-version: [14.x, 15.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: install
      run:
        npm install
    
    - name: bootstrap
      run:
        npm run bootstrap
    
    - name: lint
      run:
        npm run lint
    
    - name: coverage
      run:
        npm run coverage

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
    
    - uses: EndBug/add-and-commit@v7
      with:
        message: 'chore(${{ env.NAME }}) lint using actions'
